### ISSUE TITLE
Apollo Dev tools aren't available in firefox

### ISSUE THREAD

**Issue by wesbos** [wesbos/advanced-react-rerecord#24]
Might need to switch back to chrome for the re-record. 

Tracking it here: https://github.com/apollographql/apollo-client-devtools/issues/73

**Comment by phatcatmatt** [comment]
This is a bummer.

**Comment by martinlaws** [comment]
Although Apollo devtools are no longer available in the Firefox extension store due to use of `eval` - you can technically still download the extension from GitHub and install it manually in FF 😎 

I know it's a bit hacky but has allowed me to keep developing in Firefox Dev Edition, which I much prefer to Chrome at the moment!

**Comment by GPorter43** [comment]
Looks like Firefox have just released the new apollo graphql dev tools
